### ISSUE TITLE
Rewrite inside non-equality constraints

### ISSUE THREAD

**Issue by gelisam** [gelisam/typelevel-rewrite-rules#14]
If an instance for `Show (Vec ((m + n) + o))` exists, but we need an instance for `Show (Vec (m + (n + o)))`, can this be solved by rewriting the constraint? This is tricky, because unlike equality constraints, instance constraints carry real evidence, so I can't just use `evByFiat` to manufacture a piece of evidence from thin air.

**Comment by gelisam** [comment]
CC @tscholak

**Comment by gelisam** [comment]
We're currently only rewriting under equality constraints:

https://github.com/gelisam/typelevel-rewrite-rules/blob/6c186537e2efe4e24f20891778034884afd5ec81/src/TypeLevel/Rewrite.hs#L168-L168

It should be pretty easy to do the same thing for instance constraints, by using something like `asInstanceConstraint` and making sure to re-wrap the result using `toInstanceConstraint` instead of `toEqualityConstraint` here:

https://github.com/gelisam/typelevel-rewrite-rules/blob/6c186537e2efe4e24f20891778034884afd5ec81/src/TypeLevel/Rewrite.hs#L181-L181

Neither `asInstanceConstraint` nor `toInstanceConstraint` currently exist, but they should be easy to implement using `asEqualityConstraint` and `toEqualityConstraint` as a template, using `ClassPred` instead of `EqPred`.

What I am worried about is that we are currently using `evByFiat` as evidence that the replacement is justified:

https://github.com/gelisam/typelevel-rewrite-rules/blob/6c186537e2efe4e24f20891778034884afd5ec81/src/TypeLevel/Rewrite.hs#L185-L185

And since instance constraints involve real evidence (the dictionary), using `evByFiat` might not be good enough, leading to crashes.

**Comment by tscholak** [comment]
Hey, thanks for opening this issue!

I haven't written compiler plugins myself yet, so much of what you are discussing here is new to me. Maybe we can work out if this all is safe by considering what's happening in ghc if you add equality constraints to the context, e.g.:

```haskell
class (F a (F a b) ~ F a b) => C a b

type family F a b

class Foo a where
  foo :: ()

f :: forall a b . (C a b, Foo (F a b)) => ()
f = foo @(F a (F a b))
```

**Comment by gelisam** [comment]
Dumping the core should reveal the answer, there should be some coercion converting the `Foo (F a b)` dictionary into a `Foo (F a (F a b))` dictionary.

**Comment by tscholak** [comment]
I think that's the big question: will the givens be transformed until they match the wanteds? or the other way round?

**Comment by gelisam** [comment]
I'm not sure why it matters, but if you are curious about the details of how ghc rewrites constraints and how it interacts with ghc plugins, there is a lot of material on the topic. Nicolas Frisby [wrote some notes](https://gitlab.haskell.org/ghc/ghc/-/wikis/plugins/type-checker/notes), then I joined him and a few others at ZuriHac 2020 to write [some more](https://github.com/nfrisby/tcplugins-zurihac2020/blob/master/outline.md), then he gave [a presentation on the topic](https://www.youtube.com/watch?v=sE1qWyQWWVY). Just don't waste too much time worrying about Derived constraints, because Richard Eisenberg is getting rid of them and he's been posting [a few videos about it](https://www.youtube.com/channel/UCI1Z201n-8OelkSg0DVOsng/videos).

I briefly read through a few of those documents and I think I can infer that the answer to your question is that constraints are simplified from both directions at once, but I haven't found a quote which unambiguously states that this is the case.

**Comment by gelisam** [comment]
Would you like to try pairing on this issue? Are you available tomorrow?

**Comment by gelisam** [comment]
Anyway, the Core for your example program (obtained via `-ddump-simpl -dsuppress-module-prefixes -dsuppress-uniques`) is

```haskell
f :: forall a b. (C a b, Foo (F a b)) => ()
f = \ (@ a) (@ b) ($dC :: C a b) ($dFoo :: Foo (F a b)) ->
      case eq_sel
             @ *
             @ (F a (F a b))
             @ (F a b)
             ($dC
              `cast` (N:C[0] <a>_N <b>_N :: C a b ~R# (F a (F a b) ~ F a b)))
      of co
      { __DEFAULT ->
      $dFoo `cast` (N:Foo[0] (Sym co) :: Foo (F a b) ~R# ())
      }
```

I don't have much experience reading Core, but I am guessing that `N:C[0] <a>_N <b>_N` and `N:Foo[0] (Sym co)` are both coercion expressions, which are used to cast other expressions from one type to another. In particular, since `C a b` has a single superclass constraint and no methods, I guess a `C a b` dictionary is representationally-equal to (it is "`~R#`" to) that superclass constraint `F a (F a b) ~ F a b`, and so `$dC` can be casted into whatever is the representation of `F a (F a b) ~ F a b`. I don't know what `eq_sel` is doing with that representation of `F a (F a b) ~ F a b`, but the result is bound to the variable `co`, for "coercion".

Next, the same thing happens to the `Foo (F a b)` dictionary: since `Foo` has no superclass constraint and only one method of type `()`, that dictionary is representationally-equal to `()`, and so it can be cast to `()`. However, this time `co` is involved for some reason. I am guessing that the `foo @(F a (F a b))` is normally compiled to a cast from a `Foo (F a (F a b))` dictionary to `()`, probably via the coercion `N:Foo[0] <F a (F a b)>_N`, that `Sym co` flips `co` from `F a (F a b) ~ F a b` to `F a b ~ F a (F a b)`, and that using `Sym co` instead of `<F a (F a b)>_N` somehow causes the coercion to be from `Foo (F a b)` to `()` instead of from `Foo (F a (F a b))` to `().

**Comment by gelisam** [comment]
Okay, one more guess: I think `<a>_N` means `a ~ a`!

The definition of `C` allows us to conclude that `C x y` is representationally-equal to `F x (F x y) ~ F x y`, for any `x` and `y`. So my first guess was that `N:C[0]` is polymorphic and that `<a>_N` was a fancy was of writing `@a` to specialize `x` to `a`. But since we eventually use a coercion in a similar position, I think that `<a>_N` is a coercion, not a type application.

Using a coercion instead of a type application is kind of like giving _two_ type applications: the LHS and RHS of the `~`. This is useful because we are constructing a coercion, so we might want to instantiate `x` to a different type on the LHS and the RHS. So if I was passing a coercion of type `a ~ a'` instead of `<a>_N`, I think the result would be `C a b ~R# (F a' (F a' b) ~ F a' b)`.

Now we can better understand why we need `Sym co`. If `foo` had a more interesting type, like `foo :: a -> a`, then `N:Foo[0] <x>_N` would be a coercion of type `Foo x ~R# (x -> x)`. Since we want that LHS occurrence of `x` to be `F a b`, we have to use a coercion which has `F a b` in its LHS. `co :: F a (F a b) ~ F a b` has `F a b` in its RHS, so we simply flip it in order to get it on the LHS.

**Comment by gelisam** [comment]
Okay, yet another guess: I have not been very careful in distinguishing `a ~ b` vs `a ~R# b`. If I were more careful, then it would be a lot clearer what `eq_sel` does: it extracts an `a ~R# b` from an `a ~ b`. I think I'll continue to be sloppy in that regard, because that distinction doesn't very relevant to this discussion.

**Comment by tscholak** [comment]
Hey, I was away this evening, and I'll only get to have a better look tomorrow. If you're still interested to pair up, say in the early afternoon, I'd be interested. For me it would be a great opportunity to learn.

**Comment by gelisam** [comment]
Great! I've sent you a calendar invite.
